"""The schema as it stood before Alembic

This revision is not a change. It is the shape every installed database
already has, written down so that a database created before migrations existed
can be stamped at it and carry on from here, and so that a database created
from nothing arrives at exactly the same place.

It was generated by autogenerate from the models and then checked against a
real installed database: the eleven tables, their columns and their fifty-odd
indexes are identical object for object. `tests/test_units.py` asserts that
equality on every run, because the moment the two drift apart the stamp in
`app/db/schema.py` would be recording a version the database is not at.

Nothing here ever runs against a database that already has these tables.

Revision ID: 0001_baseline
Revises:
Created: 2026-09-12
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('automation_config',
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('emergency_stop', sa.Boolean(), nullable=False),
    sa.Column('daily_application_limit', sa.Integer(), nullable=False),
    sa.Column('daily_discovery_limit', sa.Integer(), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('min_score_to_submit', sa.Float(), nullable=False),
    sa.Column('enabled_sources', sa.JSON(), nullable=False),
    sa.Column('greenhouse_boards', sa.JSON(), nullable=False),
    sa.Column('lever_boards', sa.JSON(), nullable=False),
    sa.Column('search_terms', sa.JSON(), nullable=False),
    sa.Column('location_filters', sa.JSON(), nullable=False),
    sa.Column('remote_only', sa.Boolean(), nullable=False),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('role_filters', sa.JSON(), nullable=False),
    sa.Column('excluded_companies', sa.JSON(), nullable=False),
    sa.Column('follow_up_after_days', sa.Integer(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_runs',
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('current_stage', sa.String(length=30), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('jobs_discovered', sa.Integer(), nullable=False),
    sa.Column('jobs_deduplicated', sa.Integer(), nullable=False),
    sa.Column('jobs_scored', sa.Integer(), nullable=False),
    sa.Column('jobs_eligible', sa.Integer(), nullable=False),
    sa.Column('packages_prepared', sa.Integer(), nullable=False),
    sa.Column('applications_submitted', sa.Integer(), nullable=False),
    sa.Column('action_required', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_runs_status'), ['status'], unique=False)

    op.create_table('candidates',
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=False),
    sa.Column('years_of_experience', sa.Float(), nullable=False),
    sa.Column('current_role', sa.String(length=200), nullable=False),
    sa.Column('experience', sa.JSON(), nullable=False),
    sa.Column('education', sa.JSON(), nullable=False),
    sa.Column('projects', sa.JSON(), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('achievements', sa.JSON(), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('target_locations', sa.JSON(), nullable=False),
    sa.Column('target_countries', sa.JSON(), nullable=False),
    sa.Column('remote_only', sa.Boolean(), nullable=False),
    sa.Column('accepts_hybrid', sa.Boolean(), nullable=False),
    sa.Column('accepts_onsite', sa.Boolean(), nullable=False),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=False),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=False),
    sa.Column('seniority_targets', sa.JSON(), nullable=False),
    sa.Column('excluded_companies', sa.JSON(), nullable=False),
    sa.Column('excluded_keywords', sa.JSON(), nullable=False),
    sa.Column('excluded_industries', sa.JSON(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_is_active'), ['is_active'], unique=False)

    op.create_table('email_accounts',
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('smtp_host', sa.String(length=200), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('imap_host', sa.String(length=200), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('credential_ref', sa.String(length=200), nullable=False),
    sa.Column('oauth_scopes', sa.JSON(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_accounts_address'), ['address'], unique=False)

    op.create_table('email_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_templates_name'), ['name'], unique=False)

    op.create_table('jobs',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_job_id', sa.String(length=200), nullable=False),
    sa.Column('canonical_url', sa.String(length=1000), nullable=False),
    sa.Column('application_url', sa.String(length=1000), nullable=False),
    sa.Column('application_method', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('company_domain', sa.String(length=200), nullable=False),
    sa.Column('company_logo_url', sa.String(length=1000), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('remote_type', sa.String(length=20), nullable=False),
    sa.Column('employment_type', sa.String(length=40), nullable=False),
    sa.Column('seniority', sa.String(length=20), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=False),
    sa.Column('salary_period', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('benefits', sa.JSON(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=300), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_company'), ['company'], unique=False)
        batch_op.create_index('ix_jobs_company_title', ['company', 'title'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_discovered_at'), ['discovered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_duplicate_of_id'), ['duplicate_of_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_is_excluded'), ['is_excluded'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_is_saved'), ['is_saved'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_remote_type'), ['remote_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_seniority'), ['seniority'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_source'), ['source'], unique=False)
        batch_op.create_index('ix_jobs_source_identity', ['source', 'source_job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_source_job_id'), ['source_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_title'), ['title'], unique=False)

    op.create_table('documents',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('lineage_key', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.String(length=60), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('truthfulness_passed', sa.Boolean(), nullable=False),
    sa.Column('truthfulness_findings', sa.JSON(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('generation_seconds', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_lineage_key'), ['lineage_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_truthfulness_passed'), ['truthfulness_passed'], unique=False)

    op.create_table('job_scores',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_scores_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_scores_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_scores_recommendation'), ['recommendation'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_scores_score'), ['score'], unique=False)

    op.create_table('applications',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('board_position', sa.Integer(), nullable=False),
    sa.Column('application_method', sa.String(length=30), nullable=False),
    sa.Column('application_url', sa.String(length=1000), nullable=False),
    sa.Column('action_required_reason', sa.String(length=500), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('interview_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('follow_up_due', sa.DateTime(), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('job_snapshot', sa.JSON(), nullable=False),
    sa.Column('tailored_cv_id', sa.Integer(), nullable=True),
    sa.Column('cover_letter_id', sa.Integer(), nullable=True),
    sa.Column('application_answers', sa.JSON(), nullable=False),
    sa.Column('recruiter_message', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('stage_history', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tailored_cv_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_follow_up_due'), ['follow_up_due'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_applications_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('activity_logs',
    sa.Column('event', sa.String(length=80), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_run_id'), ['run_id'], unique=False)

    op.create_table('email_messages',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('folder', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message_id', sa.String(length=400), nullable=False),
    sa.Column('thread_id', sa.String(length=400), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('to_addresses', sa.JSON(), nullable=False),
    sa.Column('cc_addresses', sa.JSON(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_html', sa.Boolean(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_messages_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_folder'), ['folder'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_thread_id'), ['thread_id'], unique=False)



def downgrade() -> None:
    """Drop everything this revision created.

    Present because Alembic expects it and because a downgrade path that lies
    is worse than one that is honest about what it does. Nothing in the
    application calls it: going below the baseline means an empty database, and
    the way to get one of those is to move the file aside.
    """
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_messages_thread_id'))
        batch_op.drop_index(batch_op.f('ix_email_messages_status'))
        batch_op.drop_index(batch_op.f('ix_email_messages_sent_at'))
        batch_op.drop_index(batch_op.f('ix_email_messages_received_at'))
        batch_op.drop_index(batch_op.f('ix_email_messages_message_id'))
        batch_op.drop_index(batch_op.f('ix_email_messages_folder'))
        batch_op.drop_index(batch_op.f('ix_email_messages_classification'))
        batch_op.drop_index(batch_op.f('ix_email_messages_application_id'))
        batch_op.drop_index(batch_op.f('ix_email_messages_account_id'))

    op.drop_table('email_messages')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_run_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_level'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_job_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_event'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_application_id'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_applications_stage'))
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))
        batch_op.drop_index(batch_op.f('ix_applications_is_archived'))
        batch_op.drop_index(batch_op.f('ix_applications_follow_up_due'))
        batch_op.drop_index(batch_op.f('ix_applications_candidate_id'))

    op.drop_table('applications')
    with op.batch_alter_table('job_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_scores_score'))
        batch_op.drop_index(batch_op.f('ix_job_scores_recommendation'))
        batch_op.drop_index(batch_op.f('ix_job_scores_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_scores_candidate_id'))

    op.drop_table('job_scores')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_truthfulness_passed'))
        batch_op.drop_index(batch_op.f('ix_documents_lineage_key'))
        batch_op.drop_index(batch_op.f('ix_documents_kind'))
        batch_op.drop_index(batch_op.f('ix_documents_job_id'))
        batch_op.drop_index(batch_op.f('ix_documents_is_current'))
        batch_op.drop_index(batch_op.f('ix_documents_candidate_id'))

    op.drop_table('documents')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_title'))
        batch_op.drop_index(batch_op.f('ix_jobs_stage'))
        batch_op.drop_index(batch_op.f('ix_jobs_source_job_id'))
        batch_op.drop_index('ix_jobs_source_identity')
        batch_op.drop_index(batch_op.f('ix_jobs_source'))
        batch_op.drop_index(batch_op.f('ix_jobs_seniority'))
        batch_op.drop_index(batch_op.f('ix_jobs_remote_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_posted_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_is_saved'))
        batch_op.drop_index(batch_op.f('ix_jobs_is_excluded'))
        batch_op.drop_index(batch_op.f('ix_jobs_duplicate_of_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_discovered_at'))
        batch_op.drop_index(batch_op.f('ix_jobs_country'))
        batch_op.drop_index(batch_op.f('ix_jobs_content_hash'))
        batch_op.drop_index('ix_jobs_company_title')
        batch_op.drop_index(batch_op.f('ix_jobs_company'))

    op.drop_table('jobs')
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_templates_name'))
        batch_op.drop_index(batch_op.f('ix_email_templates_category'))

    op.drop_table('email_templates')
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_accounts_address'))

    op.drop_table('email_accounts')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_is_active'))
        batch_op.drop_index(batch_op.f('ix_candidates_full_name'))

    op.drop_table('candidates')
    with op.batch_alter_table('automation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_runs_status'))
        batch_op.drop_index(batch_op.f('ix_automation_runs_started_at'))

    op.drop_table('automation_runs')
    op.drop_table('automation_config')
